name: Daily Security
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  osv-scan:
    name: osv scanner run
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: rep checkout
        uses: actions/checkout@v4
      - name: osv scanner run
        uses: google/osv-scanner/actions/scanner@v2.0.2
        with:
          args: '--format sarif --output osv.sarif ./app'
      - name: osv sarif report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv.sarif
  semgrep-scan:
    name: Scan semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    container:
      image: returntocorp/semgrep
    steps:
      - name: rep check
        uses: actions/checkout@v4
      - name: semgrep jqvq rules
        run: |
          cd app
          semgrep scan --config p/java --sarif > ../semgrep.sarif
      - name: report semgrep
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
